#!/bin/bash

NAME=`echo "$0"|sed -e "s/^.*_//g"`

if [ "$NAME" == "countries" ]; then
	NAME_SINGULAR="country/countries"
elif [ "$NAME" == "flags" ]; then
	NAME_SINGULAR="flag(s)"
else
	echo "Invalid plugin name. Dying now."
	exit 3
fi

MISSING=`echo "SELECT COUNT(*) FROM missing_$NAME" | mysql -u nagios_check -pXXXXXXXX torstatus|tail -n 1`
if [ "$MISSING" -eq "0" ]; then
	echo "Everything fine, no $NAME missing."
	exit 0
fi

echo "$MISSING $NAME_SINGULAR missing."
if [ "$MISSING" -gt 3 ]; then
	exit 2
elif [ "$MISSING" -gt 0 ]; then
	exit 1
fi

