#!/bin/bash

# Usage: check_munin_alerts <munin HTTP host overview page>

if [ "$1" == "" ]; then
	echo "Usage: $0 <filename>"
	exit 3
fi

FILE=$1
if [ ! -f "$1" ]; then
	echo "File $1 not found"
	exit 3
fi

DELETE=0
IGNORE=$2
if [ "$IGNORE" == "" ]; then
	IGNORE=$(mktemp /tmp/tmpfile.XXXXX)
	DELETE=1
fi

parse() {
	FILE=$1
	CLASS=$2
	IGNORE=$3

	cat "$FILE" \
		| hxnormalize -x \
		| hxselect -s '\n' "img[class~=\"$CLASS\"]" \
		| sed -n 's/.*src="\([^"]*\)".*/\1/p' \
		| sed 's#.*/##' \
		| sed 's/-[^-]*$//' \
		| sort -u \
		| grep -cvxFf "$IGNORE"
}

WARNING=`parse "$FILE" iwarn "$IGNORE"`
CRITICAL=`parse "$FILE" icrit "$IGNORE"`
UNKNOWN=`parse "$FILE" iunkn "$IGNORE"`

if [ "$DELETE" -eq "1" ]; then
	rm -f "$IGNORE"
fi

echo "Munin status: $WARNING/$CRITICAL/$UNKNOWN (warning/critical/unknown)"

if [ "$UNKNOWN" -gt 0 ]; then
	exit 3
fi

if [ "$CRITICAL" -gt 0 ]; then
	exit 2
fi

if [ "$WARNING" -gt 0 ]; then
	exit 1
fi

exit 0

