#!/bin/bash
DIRECTORY=/etc/icinga/sms_backup

COUNT=`find $DIRECTORY/ -type f -mtime -1.1|wc -l`
FILENAME=`find $DIRECTORY -mindepth 2 -type f -printf '%T@ %p\n'| sort -n | tail -1 | cut -f2- -d" "`

echo Last SMS backup: `stat $FILENAME|grep Modify|sed -e "s/Modify: //g"`

if [ "$COUNT" -eq 0 ]; then
	exit 2
fi
exit 0

