#!/bin/bash
warning=1728000
critical=864000
for cert in `cat $1`; do
	critical_state=0
	warning_state=0
	openssl x509 -in $cert -checkend $critical -out /dev/null || critical_state=1
	openssl x509 -in $cert -checkend $warning -out /dev/null || warning_state=1
	if [ "$critical_state" -eq "1" ]; then
		echo "Certificate $cert will expire shortly."
		exit 2
	fi
	if [ "$warning_state" -eq "1" ]; then
		echo "Certificate $cert will expire shortly."
		exit 1
	fi
done
echo "None of the certificates will expire shortly."

