#!/bin/bash

LOGFILE=/var/log/pfclient/tcpdump.log

FILEAGE=`/usr/lib/nagios/plugins/check_file_age -w 600 -c 900 -f "$LOGFILE"`
EXITCODE=$?

if [ "$EXITCODE" -ne "0" ]; then
    echo $FILEAGE|sed -e 's/ |.*//'
    exit $EXITCODE
fi

COUNT=`tail -n 20 "$LOGFILE" | grep -c 'HTTP/1.1 200 OK'`

if [ "$COUNT" -eq "0" ]; then
	echo "CRITICAL - No update sent to Planefinder recently"
	exit 2
fi

echo "OK - Update sent to Planefinder recently"

