#!/usr/bin/python3

import argparse, json, requests, time, sys, datetime as dt

parser = argparse.ArgumentParser(description = 'Check status of fr24feed')
parser.add_argument('-w', type = int, nargs = 1, required = True, help = 'Warning time in seconds')
parser.add_argument('-c', type = int, nargs = 1, required = True, help = 'Critical time in seconds')
args = parser.parse_args()

try:
    resp = requests.get(url='http://localhost:8754/monitor.json')
except requests.exceptions.ConnectionError as e:
    print("Error fetching status URL")
    sys.exit(3)

data = json.loads(resp.text)

if 'feed_last_ac_sent_time' not in data:
    print("Unable to check last update timestamp")
    sys.exit(3)

last_send_time = int(data['feed_last_ac_sent_time'])
age = int(time.time()) - last_send_time

hour = dt.datetime.today().hour
warning = int(args.w[0])
critical = int(args.c[0])

print("Last update sent %s seconds ago" % age)
if age > critical:
    sys.exit(2)
if age > warning:
    sys.exit(1)


