#!/bin/bash

DIRECTORY=`dirname "$0"`
. "$DIRECTORY/parse_args"

ls -tral /var/log/pfclient
DATE=`grep -ah 'Successfully sent' /var/log/pfclient/pfclient-log_*| tail -n 1|sed -e "s/ \[.*$//"`
UNIXDATE1=`date -u -d "$DATE" +%s`
UNIXDATE2=`date -u +%s`
AGE=$((UNIXDATE2 - UNIXDATE1))

. "$DIRECTORY/print_status"

