#!/bin/bash

DIRECTORY=`dirname "$0"`
. "$DIRECTORY/parse_args"

DATE=`grep -a 'Packets sent' /var/log/rbfeeder.log|tail -n 1|sed -e "s/^.//;s/\].*$//"`
UNIXDATE1=`date -d "$DATE" +%s`
UNIXDATE2=`date +%s`
AGE=$((UNIXDATE2 - UNIXDATE1))

. "$DIRECTORY/print_status"

